"use server";
import { getCurrentUser } from "@/lib/auth";
import { query, withTransaction } from "@/lib/db";
import { revalidatePath } from "next/cache";
import { redirect } from "next/navigation";

type Game = { id: string; x_player_id: string | null; o_player_id: string | null; board_state: string; current_turn: "X" | "O"; status: string };
async function player() { const user = await getCurrentUser(); if (!user) throw new Error("Unauthorized"); return user; }
async function clearWaiting(userId: string) { await query("DELETE FROM ttt_games WHERE status='waiting' AND (x_player_id=$1 OR o_player_id=$1)", [userId]); await query("DELETE FROM chess_games WHERE status='waiting' AND (white_player_id=$1 OR black_player_id=$1)", [userId]); }

export async function createTttGame(preferredSymbol: "X" | "O" | "random" = "random") { const user = await player(); await clearWaiting(user.id); const x = preferredSymbol === "X" || (preferredSymbol === "random" && Math.random() > .5) ? user.id : null; const o = preferredSymbol === "O" || (preferredSymbol === "random" && !x) ? user.id : null; const { rows } = await query<{id:string}>("INSERT INTO ttt_games (x_player_id,o_player_id,board_state) VALUES ($1,$2,'---------') RETURNING id", [x,o]); redirect(`/dashboard/ttt/${rows[0].id}`); }
export async function challengeUserToTtt(targetUserId: string) { const user = await player(); if (!targetUserId || targetUserId === user.id) throw new Error("Invalid challenge target"); await clearWaiting(user.id); const { rows } = await query<{id:string}>("INSERT INTO ttt_games (x_player_id,o_player_id,board_state) VALUES ($1,$2,'---------') RETURNING id", [user.id,targetUserId]); revalidatePath(`/profile/${targetUserId}`); redirect(`/dashboard/ttt/${rows[0].id}`); }
export async function acceptTttChallenge(gameId: string) { const user = await player(); const {rowCount}=await query("UPDATE ttt_games SET status='in_progress',updated_at=now() WHERE id=$1 AND o_player_id=$2 AND x_player_id IS NOT NULL AND status='waiting'",[gameId,user.id]); if(!rowCount) throw new Error("Failed to accept challenge"); redirect(`/dashboard/ttt/${gameId}`); }
export async function joinTttGame(gameId: string) { const user=await player(); const {rows}=await query<Game>("SELECT * FROM ttt_games WHERE id=$1",[gameId]); const game=rows[0]; if(!game||game.status!=="waiting") throw new Error("Game is no longer available"); if(game.x_player_id===user.id||game.o_player_id===user.id) redirect(`/dashboard/ttt/${gameId}`); const column=game.x_player_id?"o_player_id":"x_player_id"; const {rowCount}=await query(`UPDATE ttt_games SET ${column}=$1,status='in_progress',updated_at=now() WHERE id=$2 AND status='waiting' AND ${column} IS NULL`,[user.id,gameId]); if(!rowCount) throw new Error("Game was just joined by someone else"); redirect(`/dashboard/ttt/${gameId}`); }
export async function cancelTttGame(gameId:string){const user=await player();await query("DELETE FROM ttt_games WHERE id=$1 AND status='waiting' AND (x_player_id=$2 OR o_player_id=$2)",[gameId,user.id]);revalidatePath("/dashboard");}
function winner(board:string){for(const [a,b,c] of [[0,1,2],[3,4,5],[6,7,8],[0,3,6],[1,4,7],[2,5,8],[0,4,8],[2,4,6]])if(board[a]!=="-"&&board[a]===board[b]&&board[a]===board[c])return board[a];return null;}
export async function makeTttMove(gameId:string,index:number){const user=await player();if(!Number.isInteger(index)||index<0||index>8)throw new Error("Invalid move");const status=await withTransaction(async client=>{const {rows}=await client.query<Game>("SELECT * FROM ttt_games WHERE id=$1 FOR UPDATE",[gameId]);const game=rows[0];if(!game||game.status!=="in_progress")throw new Error("Game not active");const symbol=game.x_player_id===user.id?"X":game.o_player_id===user.id?"O":null;if(!symbol||symbol!==game.current_turn)throw new Error("Not your turn");if(game.board_state[index]!=="-")throw new Error("Square already taken");const board=game.board_state.split("");board[index]=symbol;const win=winner(board.join(""));const nextStatus=win?`${win.toLowerCase()}_won`:board.includes("-")?"in_progress":"draw";const nextTurn=symbol==="X"?"O":"X";await client.query("UPDATE ttt_games SET board_state=$1,current_turn=$2,status=$3,winner_id=CASE WHEN $3='x_won' THEN x_player_id WHEN $3='o_won' THEN o_player_id ELSE NULL END,updated_at=now() WHERE id=$4",[board.join(""),nextTurn,nextStatus,gameId]);return nextStatus;});revalidatePath(`/dashboard/ttt/${gameId}`);return status;}
export async function resignTttGame(gameId:string){const user=await player();const {rows}=await query<Game>("SELECT * FROM ttt_games WHERE id=$1",[gameId]);const game=rows[0];if(!game||game.status!=="in_progress")throw new Error("Game not active");const status=game.x_player_id===user.id?"o_won":game.o_player_id===user.id?"x_won":null;if(!status)throw new Error("Not a player in this game");await query("UPDATE ttt_games SET status=$1,winner_id=CASE WHEN $1='x_won' THEN x_player_id ELSE o_player_id END,updated_at=now() WHERE id=$2",[status,gameId]);revalidatePath(`/dashboard/ttt/${gameId}`);}
export async function createTttRematch(oldGameId:string){const user=await player();const {rows}=await query<Game>("SELECT * FROM ttt_games WHERE id=$1",[oldGameId]);const old=rows[0];if(!old||(old.x_player_id!==user.id&&old.o_player_id!==user.id))throw new Error("Unauthorized to rematch this game");const {rows:created}=await query<{id:string}>("INSERT INTO ttt_games (x_player_id,o_player_id,status,board_state,current_turn) VALUES ($1,$2,'in_progress','---------','X') RETURNING id",[old.o_player_id,old.x_player_id]);return created[0].id;}
