"use server";
import { getCurrentUser } from "@/lib/auth";
import { query, withTransaction } from "@/lib/db";
import { revalidatePath } from "next/cache";

async function admin() { const user=await getCurrentUser(); if(!user) throw new Error("Unauthorized"); const {rows}=await query<{role:string}>("SELECT role FROM profiles WHERE id=$1",[user.id]); if(rows[0]?.role!=="admin") throw new Error("Unauthorized: Admins only"); return user; }
export async function resetSeason() { await admin(); await withTransaction(async client=>{const {rows}=await client.query<{current_season:number}>("SELECT current_season FROM system_settings WHERE id=1");const season=rows[0]?.current_season??1;const {rows:players}=await client.query("SELECT id,total_xp FROM profiles WHERE role='employee' ORDER BY total_xp DESC,full_name ASC LIMIT 3");for(const [i,p] of players.entries()) await client.query("INSERT INTO season_winners(season_number,user_id,rank,total_xp) VALUES($1,$2,$3,$4)",[season,p.id,i+1,p.total_xp??0]);for(const table of ["chess_events","challenge_events","game_spectators","direct_messages","question_history","daily_sessions","chess_games","ttt_games","connect_four_games","activity_feed","questions"]) await client.query(`DELETE FROM ${table}`);await client.query("UPDATE profiles SET total_xp=0,current_streak=0,best_streak=0,current_level=1,games_played=0,lounge_lp=0 WHERE role='employee'");await client.query("UPDATE system_settings SET current_season=$1,season_start_date=now(),updated_at=now() WHERE id=1",[season+1]);});revalidatePath("/", "layout");}
export async function getSystemSettings() { await admin(); const {rows}=await query("SELECT * FROM system_settings WHERE id=1"); return rows[0]??{current_season:1,season_start_date:new Date().toISOString(),cooldown_hours:24,daily_time_limit_minutes:15}; }
export async function updateSystemSettings(formData:FormData) { await admin();const cooldown=Math.max(0,Number(formData.get("cooldown_hours"))||0);const minutes=Math.max(1,Number(formData.get("game_duration_minutes"))||15);await query("INSERT INTO system_settings(id,current_season,season_start_date,cooldown_hours,daily_time_limit_minutes) VALUES(1,1,now(),$1,$2) ON CONFLICT(id) DO UPDATE SET cooldown_hours=$1,daily_time_limit_minutes=$2,updated_at=now()",[cooldown,minutes]);await query("UPDATE daily_sessions SET allowed_duration_seconds=$1 WHERE created_at>=CURRENT_DATE AND user_id IN (SELECT id FROM profiles WHERE session_time_limit_minutes IS NULL)",[minutes*60]);revalidatePath("/admin");revalidatePath("/admin/settings");revalidatePath("/dashboard");}
export async function factoryResetPlatform() { await admin(); await withTransaction(async client=>{for(const table of ["season_winners","chess_events","challenge_events","game_spectators","direct_messages","question_history","daily_sessions","questions","chess_games","ttt_games","connect_four_games","activity_feed"]) await client.query(`DELETE FROM ${table}`);await client.query("UPDATE profiles SET total_xp=0,current_streak=0,best_streak=0,current_level=1,games_played=0,lounge_lp=0 WHERE role='employee'");await client.query("UPDATE system_settings SET current_season=1,season_start_date=now(),updated_at=now() WHERE id=1");});revalidatePath("/", "layout");}
export async function bulkUpdateTimeLimits(dailyLimit:number,sessionLimit:number){await admin();if(!Number.isInteger(dailyLimit)||dailyLimit<0||dailyLimit>1440||!Number.isInteger(sessionLimit)||sessionLimit<0||sessionLimit>1440)throw new Error("Time limits must be whole numbers between 0 and 1440 minutes.");await query("UPDATE profiles SET daily_time_limit_minutes=$1,session_time_limit_minutes=$2 WHERE role='employee'",[dailyLimit===0?null:dailyLimit,sessionLimit===0?null:sessionLimit]);revalidatePath("/admin/settings");revalidatePath("/admin/users");}

