"use client";

import { ArrowRight, Brain, Check, Clock3, Map, Swords, Zap } from "lucide-react";

export default function OfficeWorldJourney() {
  const enter = (mode: "mission" | "lounge") => {
    document.getElementById("tour-daily-mission")?.classList.toggle("hidden", mode !== "mission");
    document.getElementById("tour-office-lounge")?.classList.toggle("hidden", mode !== "lounge");
    document.getElementById("office-world-journey")?.scrollIntoView({ behavior: "smooth", block: "start" });
  };
  const stops = [{ name: "Warm up", icon: Brain, done: true }, { name: "Think fast", icon: Zap, done: false }, { name: "Final round", icon: Check, done: false }];
  return <section id="office-world-journey" className="rounded-3xl border border-border/60 bg-card shadow-sm">
    <div className="border-b border-border/60 px-6 py-5 sm:px-8"><div className="flex items-center gap-2 text-xs font-black uppercase tracking-[0.18em] text-primary"><Map size={14}/> Today in Office Games</div><div className="mt-2 flex flex-col justify-between gap-2 sm:flex-row sm:items-end"><div><h2 className="text-2xl font-black tracking-tight sm:text-3xl">Choose your next move</h2><p className="mt-1 text-sm font-medium text-muted-foreground">One short mission, or a quick match with your team.</p></div><span className="text-xs font-bold text-muted-foreground">0 of 3 stops complete</span></div></div>
    <div className="grid gap-5 p-5 sm:p-7 lg:grid-cols-[1.25fr_.75fr]">
      <button onClick={() => enter("mission")} className="group relative overflow-hidden rounded-2xl bg-gradient-to-br from-primary to-primary/75 p-6 text-left text-primary-foreground shadow-lg shadow-primary/15 transition-transform hover:-translate-y-0.5 sm:p-7"><div className="absolute -right-8 -top-10 text-white/10"><Brain size={180}/></div><div className="relative"><div className="flex items-center justify-between"><span className="rounded-full bg-white/15 px-3 py-1 text-[10px] font-black uppercase tracking-widest">Your daily path</span><Clock3 size={19} className="opacity-80"/></div><h3 className="mt-8 text-3xl font-black tracking-tight">Daily Mission</h3><p className="mt-2 max-w-md text-sm font-medium leading-6 text-primary-foreground/80">Complete three quick challenges, build your streak, and leave with a little more energy than you started with.</p><div className="mt-7 flex items-center gap-2 text-sm font-black">Start the journey <ArrowRight size={18} className="transition-transform group-hover:translate-x-1"/></div></div></button>
      <button onClick={() => enter("lounge")} className="group rounded-2xl border border-border/60 bg-background/60 p-6 text-left transition-all hover:-translate-y-0.5 hover:border-violet-500/50 hover:shadow-md sm:p-7"><div className="flex items-center justify-between"><div className="flex h-11 w-11 items-center justify-center rounded-xl bg-violet-500/12 text-violet-500"><Swords size={22}/></div><span className="rounded-full bg-violet-500/10 px-3 py-1 text-[10px] font-black uppercase tracking-widest text-violet-500">Social</span></div><h3 className="mt-7 text-2xl font-black tracking-tight">Office Lounge</h3><p className="mt-2 text-sm font-medium leading-6 text-muted-foreground">Challenge a coworker or join a live game of Chess, Tic-Tac-Toe, or Connect Four.</p><div className="mt-6 flex items-center gap-2 text-sm font-black text-violet-500">Enter the lounge <ArrowRight size={18} className="transition-transform group-hover:translate-x-1"/></div></button>
    </div>
    <div className="px-5 pb-6 sm:px-7 sm:pb-7"><div className="rounded-2xl border border-border/60 bg-background/50 p-4 sm:p-5"><div className="mb-4 flex items-center justify-between"><span className="text-xs font-black uppercase tracking-widest text-muted-foreground">Mission route</span><span className="text-xs font-bold text-primary">10–15 min</span></div><div className="grid grid-cols-3 gap-2 sm:gap-5">{stops.map((stop, index) => { const Icon = stop.icon; return <div key={stop.name} className="relative flex items-center gap-2 sm:gap-3"><div className={`flex h-9 w-9 shrink-0 items-center justify-center rounded-xl ${stop.done ? "bg-emerald-500/15 text-emerald-500" : "bg-secondary text-muted-foreground"}`}><Icon size={16}/></div><div className="min-w-0"><p className="truncate text-xs font-black sm:text-sm">{stop.name}</p><p className="hidden text-[10px] font-medium text-muted-foreground sm:block">{stop.done ? "Ready" : "Up next"}</p></div>{index < stops.length - 1 && <div className="absolute -right-2 top-4 hidden h-px w-3 bg-border sm:block"/>}</div>; })}</div></div></div>
  </section>;
}

