import Link from "next/link";
import { ArrowRight, Brain, Check, ChevronRight, Clock3, Gamepad2, Map, Sparkles, Swords, Users, Zap } from "lucide-react";

const stops = [
  { name: "Warm up", detail: "Get in the zone", icon: Brain, done: true },
  { name: "Think fast", detail: "Test your focus", icon: Zap, done: false },
  { name: "Final round", detail: "Finish strong", icon: Check, done: false },
];

export default function OfficeWorldJourney() {
  return <section id="office-world-journey" className="relative overflow-hidden rounded-[2rem] border border-border/60 bg-card shadow-xl shadow-primary/5">
    <div className="pointer-events-none absolute -right-24 -top-24 h-64 w-64 rounded-full bg-primary/10 blur-3xl" />
    <div className="relative border-b border-border/60 px-6 py-6 sm:px-8 sm:py-7">
      <div className="flex flex-wrap items-center justify-between gap-3"><div className="flex items-center gap-2 text-xs font-black uppercase tracking-[0.18em] text-primary"><Map size={14}/> Today in Office Games</div><div className="flex items-center gap-2 rounded-full bg-emerald-500/10 px-3 py-1.5 text-xs font-bold text-emerald-600"><Sparkles size={13}/> Two ways to play</div></div>
      <div className="mt-4 max-w-2xl"><h2 className="text-3xl font-black tracking-tight sm:text-4xl">Choose your next move</h2><p className="mt-2 text-sm font-medium leading-6 text-muted-foreground">Make a little progress on your own, or bring your team into the game.</p></div>
    </div>
    <div className="relative grid items-stretch gap-5 p-5 sm:p-7 lg:grid-cols-2">
      <Link href="/daily-mission" className="group relative min-h-[250px] overflow-hidden rounded-3xl border border-primary/20 bg-background/70 p-6 text-left shadow-sm transition-all duration-300 hover:-translate-y-1 hover:border-primary/60 hover:bg-primary/[0.04] hover:shadow-xl sm:p-8">
        <div className="absolute -right-10 -top-12 text-primary/10 transition-transform duration-500 group-hover:scale-110 group-hover:rotate-6"><Brain size={220}/></div><div className="relative flex h-full flex-col"><div className="flex items-center justify-between"><span className="rounded-full bg-primary/10 px-3 py-1.5 text-[10px] font-black uppercase tracking-widest text-primary">Your daily path</span><Clock3 size={19} className="text-primary/60"/></div><div className="mt-auto pt-10"><div className="mb-2 flex items-center gap-2 text-xs font-bold text-muted-foreground"><Gamepad2 size={14} className="text-primary"/> Solo challenge · 10–15 min</div><h3 className="text-3xl font-black tracking-tight">Daily Mission</h3><p className="mt-2 max-w-md text-sm font-medium leading-6 text-muted-foreground">A quick mix of brain games designed to build your streak and leave you feeling sharper.</p><div className="mt-6 inline-flex items-center gap-2 text-sm font-black text-primary">Start the journey <ArrowRight size={18} className="transition-transform group-hover:translate-x-1"/></div></div></div>
      </Link>
      <Link href="/office-lounge" className="group relative min-h-[250px] overflow-hidden rounded-3xl border border-border/60 bg-background/70 p-6 text-left transition-all duration-300 hover:-translate-y-1 hover:border-violet-500/50 hover:bg-violet-500/[0.03] hover:shadow-xl sm:p-8">
        <div className="flex items-center justify-between"><div className="flex h-12 w-12 items-center justify-center rounded-2xl bg-violet-500/10 text-violet-500 transition-transform duration-300 group-hover:rotate-6 group-hover:scale-110"><Swords size={23}/></div><span className="rounded-full bg-violet-500/10 px-3 py-1.5 text-[10px] font-black uppercase tracking-widest text-violet-500">Social</span></div><div className="mt-9"><div className="mb-2 flex items-center gap-2 text-xs font-bold text-muted-foreground"><Users size={14}/> Multiplayer · Watch or play</div><h3 className="text-3xl font-black tracking-tight">Office Lounge</h3><p className="mt-2 text-sm font-medium leading-6 text-muted-foreground">Challenge a coworker, join a live match, or watch the office competition unfold.</p><div className="mt-6 inline-flex items-center gap-2 text-sm font-black text-violet-500">Enter the lounge <ArrowRight size={18} className="transition-transform group-hover:translate-x-1"/></div></div>
      </Link>
    </div>
    <div className="relative px-5 pb-6 sm:px-7 sm:pb-7"><div className="rounded-3xl border border-border/60 bg-background/60 p-5 sm:p-6"><div className="mb-5 flex flex-wrap items-center justify-between gap-2"><div><p className="text-xs font-black uppercase tracking-widest text-muted-foreground">Daily mission route</p><p className="mt-1 text-xs font-medium text-muted-foreground">Three short stops. One satisfying finish.</p></div><span className="rounded-full bg-primary/10 px-3 py-1.5 text-xs font-black text-primary">10–15 min</span></div><div className="grid gap-3 sm:grid-cols-3">{stops.map((stop, index) => { const Icon = stop.icon; return <div key={stop.name} className="group/stop relative flex items-center gap-3 rounded-2xl border border-border/50 bg-card/60 p-3 transition-colors hover:border-primary/30"><div className={`flex h-10 w-10 shrink-0 items-center justify-center rounded-xl ${stop.done ? "bg-emerald-500/15 text-emerald-500" : "bg-secondary text-muted-foreground"}`}><Icon size={17}/></div><div className="min-w-0"><p className="truncate text-sm font-black">{stop.name}</p><p className="truncate text-[11px] font-medium text-muted-foreground">{stop.detail}</p></div>{index < stops.length - 1 && <ChevronRight className="absolute -right-3 z-10 hidden text-border sm:block" size={18}/>}</div>; })}</div></div></div>
  </section>;
}
